server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssda
    username: root
    password: Dongcci92!!
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: gkgk9753@gmail.com
    password: hqqd aezh ppxf rcxg
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7


#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://118.67.143.25:3306/ssda
#    username: ssda
#    password: 1234
#  redis:
#    host: 172.17.0.1
#    port: 6379
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: gkgk9753@gmail.com
#    password: hqqd aezh ppxf rcxg
#    properties:
#      mail:
#        smtp:
#          auth: true # 5
#          timeout: 5000 # 6
#          starttls:
#            enable: true # 7

jpa:
  properties:
    hibernate:
      show_sql: true
      format_sql: true
  hibernate:
    ddl-auto: update
  database-platform: org.hibernate.dialect.MySQL8Dialect

logging:
  level:
    org:
      springframework:
        boot: DEBUG
      hibernate:
        type:
          descriptor:
            sql: trace

servlet:
  multipart:
    maxFileSize: 20MB
    maxRequestSize: 100MB

itemImgLocation: /Users/proxy/items/item/
uploadPath: file:/Users/proxy/items/

#itemImgLocation: /app/items
#uploadPath: /app


jwt:
  secret-key: GaXmsBiD6L1Z2M3NorAExZp8gr3uPXDR6J6iZxe4pfYKTf0SV1+I0xGqmuPG+nmLVCl9/2+lYB/VFI+AgoFGpg==

oauth:
  kakao:
    client-id: 992ac8b159b158f4299b493df0509202
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com

